(function() {var implementors = {};
implementors['hound'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='hound/enum.Error.html' title='hound::Error'>Error</a>",];implementors['vorbis'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='vorbis/enum.VorbisError.html' title='vorbis::VorbisError'>VorbisError</a>",];implementors['time'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='time/enum.ParseError.html' title='time::ParseError'>ParseError</a>",];implementors['cpal'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='cpal/enum.FormatsEnumerationError.html' title='cpal::FormatsEnumerationError'>FormatsEnumerationError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='cpal/enum.CreationError.html' title='cpal::CreationError'>CreationError</a>",];implementors['rodio'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='cpal/enum.FormatsEnumerationError.html' title='cpal::FormatsEnumerationError'>FormatsEnumerationError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/std/error/trait.Error.html' title='std::error::Error'>Error</a> for <a class='enum' href='cpal/enum.CreationError.html' title='cpal::CreationError'>CreationError</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
